const mongoose = require("mongoose");
const userSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    email: { type: String, required: true },
    country_code: { type: String, required: true },
    mobile: { type: String, required: true },
    gender: {
      type: String,
      required: true,
    },
    profile_for: { type: String, required: false },
    password: { type: String, required: true },
    confirmPassword: { type: String, required: false },
    blood_group: { type: String, required: false },
    caste: { type: String, required: false },
    weight: { type: String, required: false },
    about_me: { type: String, required: false },
    height: { type: String, required: false },
    qualification: { type: String, required: false },
    occupation: { type: String, required: false },
    income: { type: String, required: false },
    organisation_name: { type: String, required: false },
    city: { type: String, required: false },
    state: { type: String, required: false },
    current_address: { type: String, required: false },
    pin: { type: Number, required: false },
    whatsapp_no: { type: String, required: false },
    challenged: { type: String, required: false },
    permanent_address: { type: String, required: false },
    marital_status: { type: String, required: false },
    aadhaar: { type: String, required: false },
    dob: { type: String, required: false },
    birth_place: { type: String, required: false },
    birth_time: { type: String, required: false },
    manglik: { type: String, required: false },
    gotra: { type: String, required: false },
    gotra_nanihal: { type: String, required: false },
    family_address: { type: String, required: false },
    father_name: { type: String, required: false },
    father_occupation: { type: String, required: false },
    family_status: { type: String, required: false },
    family_district: { type: String, required: false },
    mother_name: { type: String, required: false },
    grand_father_name: { type: String, required: false },
    mother_occupation: { type: String, required: false },
    family_type: { type: String, required: false },
    family_income: { type: String, required: false },
    family_city: { type: String, required: false },
    mobile2: { type: String, required: false },
    brother: { type: String, required: false },
    sister: { type: String, required: false },
    drinking: { type: String, required: false },
    dietary: { type: String, required: false },
    hobbies: { type: String, required: false },
    smoking: { type: String, required: false },
    language: { type: String, required: false },
    interests: { type: String, required: false },
    working: {
      type: Number,
      required: false,
    },
    image: { type: String, required: false },
    end_subscription_date: {
      type: String,
      required: false,
    },
    isActive: { type: Boolean, required: false, default: true },
  },
  { timestamps: true }
);

module.exports = mongoose.model("User", userSchema);
