const mongoose = require('mongoose');
const userSchema = new mongoose.Schema({
  name: { type: String, required: true },
  email: { type: String, required: true },
  country_code: { type: String, required: true },
  mobile: { type: String, required: true },
  otp: { type: String, required: true },
  gender: { type: String, required: true, enum: ['1', '2'], comment: '1=male, 2=female' },
  profile_for: { type: String, required: true },
  password: { type: String, required: true },
  area_of_interest: { type: String, required: true },
  blood_group: { type: String, required: true },
  caste: { type: String, required: true },
  complexion: { type: String, required: true },
  body_type: { type: String, required: true },
  weight: { type: String, required: true },
  about_me: { type: String, required: true },
  height: { type: String, required: true },
  qualification: { type: String, required: true },
  occupation: { type: String, required: true },
  income: { type: String, required: true },
  work_place: { type: String, required: true },
  organisation_name: { type: String, required: true },
  city: { type: String, required: true },
  state: { type: String, required: true },
  district: { type: String, required: true },
  current_address: { type: String, required: true },
  pin: { type: Number, required: true },
  whatsapp_no: { type: String, required: true },
  challenged: { type: String, required: true },
  permanent_address: { type: String, required: true },
  marital_status: { type: String, required: true },
  aadhaar: { type: String, required: true },
  dob: { type: String, required: true },
  birth_place: { type: String, required: true },
  birth_time: { type: String, required: true },
  manglik: { type: String, required: true },
  gotra: { type: String, required: true },
  gotra_nanihal: { type: String, required: true },
  family_address: { type: String, required: true },
  father_name: { type: String, required: true },
  father_occupation: { type: String, required: true },
  family_status: { type: String, required: true },
  family_district: { type: String, required: true },
  mother_name: { type: String, required: true },
  grand_father_name: { type: String, required: true },
  family_state: { type: String, required: true },
  family_pin: { type: String, required: true },
  mother_occupation: { type: String, required: true },
  family_type: { type: String, required: true },
  family_income: { type: String, required: true },
  family_city: { type: String, required: true },
  maternal_grand_father_name_address: { type: String, required: true },
  family_value: { type: String, required: true },
  mobile2: { type: String, required: true },
  brother: { type: String, required: true },
  sister: { type: String, required: true },
  drinking: { type: String, required: true },
  dietary: { type: String, required: true },
  hobbies: { type: String, required: true },
  smoking: { type: String, required: true },
  language: { type: String, required: true },
  interests: { type: String, required: true },
  working: { type: Number, required: true, default: 0, enum: [0, 1], comment: '1=yes, 0=no' },
  shortlisted: { type: Number, required: true, default: 0 },
  status: { type: Number, required: true, default: 0, enum: [0, 1, 2], comment: '1=active, 0=inactive, 2=delete' },
  critical: { type: Number, required: true, default: 0 },
  device_type: { type: String, required: true },
  device_token: { type: String, required: true },
  user_avtar: { type: String, required: true, comment: 'profile image' },
  end_subscription_date: { type: String, required: true, comment: 'expiry date of subscription' },
  reasons: { type: String, required: true, comment: 'delete account reasons' },
  created_at: { type: String, required: true },
  updated_at: { type: String, required: true }
});


module.exports = mongoose.model('User', userSchema);