const mongoose = require("mongoose");
const userSchema = new mongoose.Schema(
  {
    name: { type: String, required: false },
    email: { type: String, required: true },
    country_code: { type: String, required: false },
    mobile: { type: String, required: false },
    gender: {
      type: String,
      required: false,
    },
    password: { type: String, required: false },
    confirmPassword: { type: String, required: false },
    blood_group: { type: String, required: false, default: null },
    caste: { type: String, required: false, default: null },
    weight: { type: String, required: false, default: null },
    about_me: { type: String, required: false, default: null },
    body_type: { type: String, required: false, default: null },
    height: { type: String, required: false, default: null },
    qualification: { type: String, required: false, default: null },
    occupation: { type: String, required: false, default: null },
    income: { type: String, required: false, default: null },
    organisation_name: { type: String, required: false, default: null },
    city: { type: String, required: false, default: null },
    state: { type: String, required: false, default: null },
    country: { type: String, required: false, default: null },
    district: { type: String, required: false, default: null },
    current_address: { type: String, required: false, default: null },
    pinCode: { type: String, required: false, default: null },
    whatsapp_no: { type: String, required: false, default: null },
    challenged: { type: String, required: false, default: null },
    address: { type: String, required: false, default: null },
    marital_status: { type: String, required: false, default: null },
    aadhaar: { type: String, required: false, default: null },
    dob: { type: String, required: false, default: null },
    birth_place: { type: String, required: false, default: null },
    birth_time: { type: String, required: false, default: null },
    manglik: { type: String, required: false, default: null },
    gotra: { type: String, required: false, default: null },
    gotra_nanihal: { type: String, required: false, default: null },
    family_address: { type: String, required: false, default: null },
    father_name: { type: String, required: false, default: null },
    father_occupation: { type: String, required: false, default: null },
    family_status: { type: String, required: false, default: null },
    mother_name: { type: String, required: false, default: null },
    mother_occupation: { type: String, required: false, default: null },
    family_type: { type: String, required: false, default: null },
    family_income: { type: String, required: false, default: null },
    family_city: { type: String, required: false, default: null },
    brother: { type: String, required: false, default: null },
    sister: { type: String, required: false, default: null },
    drinking: { type: String, required: false, default: null },
    dietary: { type: String, required: false, default: null },
    hobbies: { type: String, required: false, default: null },
    smoking: { type: String, required: false, default: null },
    languages: { type: String, required: false, default: null },
    image: { type: String, required: false, default: null },
    resetPasswordToken: { type: String, required: false },
    resetPasswordExpires: { type: String, required: false },
    end_subscription_date: {
      type: String,
      required: false,
      default: null,
    },
    subscription: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Package", 
      required: false,
      default: null,
    },
    isActive: { type: Boolean, required: false, default: true },
    membershipStatus: {
      type: String,
      enum: ["active", "expired"],
      default: "expired",
    },
    membershipDays: {
      type: Number,
      default: 0,
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model("User", userSchema);
